-- 코드를 입력하세요
SELECT 
    CAR_TYPE,
    COUNT(*) AS CARS
FROM 
    CAR_RENTAL_COMPANY_CAR 
WHERE 
    OPTIONS LIKE '%통풍시트%'
    OR OPTIONS LIKE '%열선시트%'
    OR OPTIONS LIKE '%가죽시트%'
# OR ('열선시트' in OPTIONS)
# OR ('후방카메라' in OPTIONS)
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE;